### ISSUE TITLE
hubApiKey not working

### ISSUE THREAD

**Issue by tonyguerrero88** [liquibase/liquibase-github-action#36]
I added hubApiKey: ${{ secrets.hubApiKey }} to my YAML file as follows and I get the following error, is this functionality not working?

`Unexpected input(s) 'hubApiKey', valid inputs are ['entryPoint', 'args', 'operation', 'classpath', 'changeLogFile', 'username', 'password', 'url', 'count', 'tag', 'date', 'referenceUrl']`

```

steps:
      - uses: actions/checkout@v2
      - run: wget https://download.oracle.com/otn-pub/otn_software/jdbc/216-OAuth2/ojdbc11.jar -O ojdbc11.jar
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update' 
          classpath: '/github/workspace/ojdbc11.jar'
          changeLogFile: '/environment/cfg/changelog.oracle.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}
          hubApiKey: ${{ secrets.hubApiKey }}

```
