### ISSUE TITLE
Request: Verbose flag

### ISSUE THREAD

**Issue by lowlydba** [liquibase/liquibase-github-action#42]
It would be helpful to be able to toggle the `verbose` flag when running compatible actions (i.e. `validate`) for debugging and testing purposes.

**Comment by mcred** [comment]
Hi, @lowlydba. We're in the process of transition over to our new verified github actions here: https://github.com/liquibase-github-actions.

They support all command parameters and global parameters. So for your example: https://github.com/liquibase-github-actions/validate does support the `logLevel` flag.

```yaml
steps:
- uses: actions/checkout@v3
- uses: liquibase-github-actions/validate@v4.17.2
  with:
    changelogFile: ""
    url: ""
    logLevel: INFO
```
