### ISSUE TITLE
spanner driver support

### ISSUE THREAD

**Issue by sangeethdba** [liquibase/liquibase-github-action#45]
Hi trying to use liquibase GH actions  to make database changes against spanner database. 
when i'm calling gh with the below details ,
Im getting  

Unexpected error running Liquibase: Driver class was not specified and could not be determined from the url (jdbc:cloudspanner:/projects/XXXXXXX

**Comment by nvoxland** [comment]
Hi, for consistency and for performance reasons we keep the container we run github actions in equivalent to what is installed with the regular liquibase installer and not adding in any additional extensions or drivers. Otherwise there gets to be no end to what we could put in there...

Instead, liquibase will look for jar files in a `liquibase_libs` directory and you can add whatever you need to that. 

For example:
```yaml
    steps:
      - uses: actions/checkout@v3

      - run: mkdir liquibase_libs

      - run: curl https://github.com/cloudspannerecosystem/liquibase-spanner/releases/download/4.17.0/liquibase-spanner-4.17.0.jar -o liquibase_libs/liquibase-spanner.jar
      - run: curl https://repo1.maven.org/maven2/com/google/cloud/google-cloud-spanner-jdbc/2.9.0/google-cloud-spanner-jdbc-2.9.0.jar -o liquibase_libs/google-cloud-spanner-jdbc.jar

      - uses: liquibase-github-actions/update@v4.18.0
        with:
          changelogFile: "com/example/changelog.xml"
          url: jdbc:cloudspanner:/projects/XXXXXXX
          ....
```

will download both the [required spanner liquibase extension](https://github.com/cloudspannerecosystem/liquibase-spanner) plus the jdbc driver.

Also notice this example uses our newer actions from https://github.com/liquibase-github-actions which are the versions we'll be supporting going forward

**Comment by nvoxland** [comment]
I ended up making a new github action that downloads jars and dependencies a bit easier. So instead of curl you can use:

```
  steps:
      - uses: actions/checkout@v3

      - uses: nvoxland/jar-download-action@main
        with:
          groupId: com.google.cloud
          artifactId: google-cloud-spanner-jdbc
          version: 2.9.0
          outputDirectory: liquibase_libs

      - run: curl https://github.com/cloudspannerecosystem/liquibase-spanner/releases/download/4.17.0/liquibase-spanner-4.17.0.jar -o liquibase_libs/liquibase-spanner.jar

      - uses: liquibase-github-actions/update@v4.18.0
        with:
          changelogFile: "com/example/changelog.xml"
          url: jdbc:cloudspanner:/projects/XXXXXXX
          ....
```

and it gets all the dependencies for google-cloud-spanner-jdbc. I don't think liquibase-spanner is on maven central, so you maybe have to keep curl'ing that one
