### ISSUE TITLE
Does not work with JDK 11

### ISSUE THREAD

**Issue by smcveigh941** [liquibase/liquibase-github-action#8]
**Steps to reproduce:**
 * Add the following step to your pipeline before calling the liquibase action
```
       - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
```

**Result:** 
`/liquibase/liquibase: line 77: /opt/hostedtoolcache/jdk/11.0.9/x64/bin/java: No such file or directory`
